#!/bin/bash

Dotfiles () {
echo " "
echo "Import Personal Dotfiles from GitHub?"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	##Update to use custom dotfiles in future
	echo "Installing Dotfiles..."
	cd /tmp
	git clone https://github.com/ajhaydock/dotfiles.git
	cd /tmp/dotfiles
	sh install.sh
  	echo "Installed Dotfiles"
	Main
	;;
	[Nn]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
